import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";
import { isClerkConfigured } from "@/lib/clerk";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "JobGeniusAI - AI Career Coach",
  description: "Generated by create next app",
  icon: "icon.png",
};

function AppShell({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/logo5.png" sizes="any" />

        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-NNGSLBEB2L"
        ></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-NNGSLBEB2L');
          `,
          }}
        />
      </head>
      <body className={`${inter.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Header />

          <main className="min-h-screen">{children}</main>

          <Toaster richColors />

          <footer className="bg-muted/50 py-12">
            <p className="text-lg font-bold container mx-auto px-4 text-center text-gray-200">
              Made by
              <a
                href="https://github.com/hailuBoc"
                className="text-yellow-400 hover:text-red-300"
                target="_blank"
              >
                {" "}
                Hailegebrel Yalember
              </a>
            </p>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}

export default function RootLayout({ children }) {
  if (!isClerkConfigured) {
    return <AppShell>{children}</AppShell>;
  }

  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <AppShell>{children}</AppShell>
    </ClerkProvider>
  );
}
